
/*FETCHING THE VALUE DYNAMICALLY USING THE DBMS_SQL PACKAGE */

CREATE OR REPLACE PROCEDURE NEW_PROC_TODAY
(
    P_EMP_NO IN EMP.EMPNO%TYPE 
)
IS
    P_CUR_NO INTEGER;
    P_TOTAL INTEGER;
    P_ENAME VARCHAR2(50);
BEGIN
    P_CUR_NO:=DBMS_SQL.OPEN_CURSOR;
    DBMS_SQL.PARSE(P_CUR_NO,'SELECT ENAME FROM EMP WHERE EMPNO=:P_EMP_NO',DBMS_SQL.NATIVE);
    DBMS_SQL.BIND_VARIABLE(P_CUR_NO,':P_EMP_NO',P_EMP_NO);
    DBMS_SQL.DEFINE_COLUMN(P_CUR_NO,1,P_ENAME,50);
    P_TOTAL:=DBMS_SQL.EXECUTE(P_CUR_NO);
    LOOP
        EXIT WHEN DBMS_SQL.FETCH_ROWS(P_CUR_NO)=0 ;
        DBMS_SQL.COLUMN_VALUE(P_CUR_NO,1,P_ENAME);
        DBMS_OUTPUT.PUT_LINE(P_ENAME);
    END LOOP;
END;

BEGIN
    NEW_PROC_TODAY(P_EMP_NO=>7698);
END;

SELECT * FROM EMP;
