SELECT ENAME,SAL,DEPTNO,
LAST_VALUE(ENAME)OVER(ORDER BY SAL ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS LAST_SAL
FROM EMP


SELECT ENAME,SAL,DEPTNO,
DENSE_RANK()OVER(PARTITION BY DEPTNO ORDER BY SAL) AS DENSE_RANK_EMP,
MAX(SAL) KEEP( DENSE_RANK LAST  ORDER BY SAL )OVER (PARTITION BY DEPTNO) AS MAX_DENSE_RANK
FROM EMP ;


SELECT ENAME,SAL,
DEPTNO,RANK()OVER(ORDER BY SAL ) 
FROM EMP;

SELECT ENAME,SAL,DEPTNO,
DENSE_RANK()OVER(ORDER BY SAL) AS D_EMP
FROM EMP



SELECT ENAME,SAL,DEPTNO,
DENSE_RANK()OVER( PARTITION BY DEPTNO ORDER BY SAL ) AS DENSE_RANK_SAL,
MIN(ENAME) KEEP(DENSE_RANK FIRST ORDER BY SAL )OVER(PARTITION BY DEPTNO) AS DENSE_MIN_SAL,
MAX(ENAME) KEEP(DENSE_RANK LAST ORDER BY SAL) OVER (PARTITION BY DEPTNO) AS DENSE_MAX_SAL
FROM EMP;
