CREATE OR REPLACE PROCEDURE INSERT_NEW_EMP_PROC
(
    P_TABLE VARCHAR2,
    P_COL_VAL NUMBER
)
IS
    V_DATA1 NUMBER:=20;
    V_DATA2 NUMBER:=30;
    V_VAR VARCHAR2(50);
BEGIN
    V_VAR:='INSERT INTO ' || P_TABLE || ' VALUES  (:1) ';
    EXECUTE IMMEDIATE V_VAR USING P_COL_VAL;
    EXECUTE IMMEDIATE V_VAR USING V_DATA1 ;
    EXECUTE IMMEDIATE V_VAR USING V_DATA2 ;
END ; --ENDING THE PROCEDURE 


DELETE FROM OLD_EMP ;

BEGIN
    INSERT_NEW_EMP_PROC(P_TABLE=>'OLD_EMP',P_COL_VAL=>10);
END;

SELECT * FROM OLD_EMP;