CREATE OR REPLACE TYPE PERSON_OBJ IS OBJECT(
    FNAME VARCHAR2(50),
    LNAME VARCHAR2(50),
    DOB DATE,
    CONSTRUCTOR FUNCTION PERSON_OBJ
    (
        FIRST_NAME VARCHAR2,
        LAST_NAME VARCHAR2,
        DOB DATE
    )RETURN SELF AS RESULT ,
    MEMBER FUNCTION FULLNAME RETURN VARCHAR2,
    MEMBER FUNCTION ONDATE RETURN DATE
) NOT FINAL ;

/* CREATING THE TYPE BODY */

CREATE OR REPLACE TYPE BODY PERSON_OBJ IS
CONSTRUCTOR FUNCTION PERSON_OBJ
    (
        FIRST_NAME VARCHAR2,
        LAST_NAME VARCHAR2,
        DOB DATE
    )
RETURN SELF AS RESULT
IS 
BEGIN
    SELF.FNAME:=FIRST_NAME;
    SELF.LNAME:=LAST_NAME;
    SELF.DOB:=DOB;
    RETURN;
END PERSON_OBJ ;
--CREATING THE FULLNAME FUNCTION 
MEMBER FUNCTION FULLNAME RETURN VARCHAR2
IS
    FULLNAME VARCHAR2(50);
BEGIN 
    FULLNAME:=SELF.FNAME || ' ' || SELF.LNAME ;
    RETURN FULLNAME ;
END FULLNAME ;
MEMBER FUNCTION ONDATE RETURN DATE
IS
BEGIN 
    RETURN SELF.DOB ;
END ONDATE ;
END ;

/* CREATING THE COLUMN OBJECT OUT OF IT WITH OBJECT TABLE */
CREATE TABLE PERSON_TBL (
    ID NUMBER,
    DETAILS PERSON_OBJ
)

/* NOW INSERTING THE ELEMENTS INTO THE TABLE */
INSERT INTO PERSON_TBL(ID,DETAILS) VALUES (101,PERSON_OBJ(FIRST_NAME=>'RIKA',LAST_NAME=>'SARANGI',DOB=>TO_DATE('16-03-1997','DD-MM-YYYY')));
INSERT INTO PERSON_TBL(ID,DETAILS) VALUES (101,PERSON_OBJ(FIRST_NAME=>'ABISMRUTA',LAST_NAME=>'SARANGI',DOB=>TO_DATE('16-03-1997','DD-MM-YYYY')));
INSERT INTO PERSON_TBL(ID,DETAILS) VALUES (101,PERSON_OBJ(FIRST_NAME=>'ABI',LAST_NAME=>'SARANGI',DOB=>TO_DATE('16-03-1997','DD-MM-YYYY')));

/*SELECTING THE ELEMENTS*/
SELECT * FROM PERSON_TBL;

/*UPDATING THE ELEMNET VALUE */
UPDATE PERSON_TBL P SET ID=102 , P.DETAILS.LNAME='PRAYAG' WHERE P.DETAILS.FNAME='ABISMRUTA';
UPDATE PERSON_TBL P SET ID=103 , P.DETAILS.LNAME='PRAYAG' WHERE P.DETAILS.FNAME='ABI';

/*USING THE FUNCTION TO FETCH THE FUILL NAME AND DATE OF BIRTH */
SELECT P.DETAILS.FULLNAME() AS FULL_NAME, TO_CHAR(P.DETAILS.ONDATE(),'MM-DD-YYYY') AS DATE_OF_BIRTH FROM PERSON_TBL P;




