/* AS ITS A FUNCTION WE CAN USE IT  IN THE SELECT BLOCK AS */

SELECT DBMS_XMLGEN.CONVERT('<RESULT/>')
FROM DUAL ;

/* ALTERNATE APPROACH*/

SELECT DBMS_XMLGEN.CONVERT
(
DBMS_XMLGEN.GETXML('SELECT * FROM DEPT') ,0
)
FROM DUAL ;

/*FETCHING THROUGH THE PLSQL RECORD */

DECLARE
    QWCTX DBMS_XMLGEN.CTXHANDLE ;
    RESULT_VAR XMLTYPE ;
    V_RESULT CLOB;
    RESULTANT VARCHAR2(3000);
BEGIN
    SELECT DBMS_XMLGEN.GETXMLTYPE('SELECT * FROM DEPT') INTO RESULT_VAR
    FROM DUAL ;
    V_RESULT:=RESULT_VAR.GETCLOBVAL;
    RESULTANT:=STANDARD.TO_CHAR(V_RESULT);
    RESULTANT:=DBMS_XMLGEN.CONVERT(RESULTANT,1);
    DBMS_OUTPUT.PUT_LINE(RESULTANT); 
END ;

/* CONVERTING THE XMLTYPE TO  CLOB DATA TO STRING AND  FETCHING THE CONVERTION */

DECLARE
        QWCTX DBMS_XMLGEN.CTXHANDLE ;
        RESULT_VAR CLOB ;
        V_RESULT VARCHAR2(3000);
        RESULTANT VARCHAR2(30000);
    BEGIN
        SELECT DBMS_XMLGEN.GETXML('SELECT * FROM DEPT') INTO RESULT_VAR
        FROM DUAL ;
        -- V_RESULT:=DBMS_XMLGEN.CONVERT(RESULT_VAR);
        V_RESULT:=STANDARD.TO_CHAR(RESULT_VAR);
        RESULTANT:=DBMS_XMLGEN.CONVERT(V_RESULT,0);
        DBMS_OUTPUT.PUT_LINE(RESULTANT);
    END ;

