
CREATE OR REPLACE PROCEDURE CREATE_ANY_TBL
(
    P_TABLE VARCHAR2,
    P_COLUMN VARCHAR2
)
IS
    P_CUR_ID NUMBER;
    P_TOTAL NUMBER;
BEGIN
    P_CUR_ID:=DBMS_SQL.OPEN_CURSOR();--OPENING THE CURSOR 
    DBMS_SQL.PARSE(P_CUR_ID,'CREATE TABLE ' || P_TABLE ||'(' || P_COLUMN ||')',DBMS_SQL.NATIVE);
    P_TOTAL:=DBMS_SQL.EXECUTE(P_CUR_ID);
    DBMS_OUTPUT.PUT_LINE('TOTAL VALUE IS ' || P_TOTAL);
END;


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE OLD_EMP';
    CREATE_ANY_TBL(P_TABLE=>'OLD_EMP',P_COLUMN=>'DATA NUMBER ');
END;

SELECT * FROM OLD_EMP;

CREATE OR REPLACE PROCEDURE PROC_OLD_EMP_INSERT_EXEC
(
    P_TABLE IN VARCHAR2,
    P_ID IN NUMBER
)
IS
    V_VAR VARCHAR2(2000);
BEGIN
    V_VAR:='INSERT INTO ' || P_TABLE || ' VALUES (:X)';
    DBMS_OUTPUT.PUT_LINE(V_VAR);
    EXECUTE IMMEDIATE V_VAR USING P_ID;
END;


BEGIN
    PROC_OLD_EMP_INSERT_EXEC('OLD_EMP',10);
END;

SELECT * FROM OLD_EMP;



CREATE OR REPLACE PROCEDURE PROC_OLD_EMP_INSERT
(
    P_TABLE IN VARCHAR2,
    P_ID IN NUMBER
)
IS
    P_CUR_ID NUMBER;
    P_TOTAL NUMBER;
    V_VAR VARCHAR2(50);
BEGIN
    P_CUR_ID:=DBMS_SQL.OPEN_CURSOR();
    V_VAR:='INSERT INTO ' || P_TABLE || ' VALUES (:P_ID)';
    DBMS_OUTPUT.PUT_LINE(V_VAR);
    DBMS_SQL.PARSE(P_CUR_ID, V_VAR,DBMS_SQL.NATIVE );
    DBMS_SQL.BIND_VARIABLE(P_CUR_ID,  ':P_ID' , P_ID );
    P_TOTAL:=DBMS_SQL.EXECUTE(P_CUR_ID );
    DBMS_OUTPUT.PUT_LINE(P_TOTAL || ' RECORDS INSERTED ');
END;

BEGIN
    PROC_OLD_EMP_INSERT(P_TABLE=>'OLD_EMP',P_ID=>20);
END;


SELECT * FROM OLD_EMP;