/* PUTTING THE XML DATA INTO A FILE */

DECLARE 
    FP UTL_FILE.FILE_TYPE;--DEFINING THE FILE_POINTER VARIABLE
    QWCTX  DBMS_XMLGEN.CTXHANDLE;--DEFINING THE CONTEXT HANDLER
    RESULT_VAR XMLTYPE ;-- DEFINING THE VALUE IS OF XML TYPE
    MY_CUR SYS_REFCURSOR;--DEFINING IT AS A SYS REF CURSOR 
BEGIN
    OPEN MY_CUR FOR SELECT * FROM DEPT ; --DEFINING THE CURSOR AND OPENING THE SAME
    QWCTX:=DBMS_XMLGEN.NEWCONTEXT(MY_CUR);--DEFINING THE CURSORAND CREATING CONTEXT HANDLER
    RESULT_VAR:=DBMS_XMLGEN.GETXMLTYPE(QWCTX);--GENERATING THE XMLTYPE XML FROM CONTEXT HANDLE
    FP:=UTL_FILE.FOPEN('EMP_DATA','EMP.XML','W');--OPENING THE FILE IN WRITE MODE
    UTL_FILE.PUT_LINE(FP,RESULT_VAR.GETCLOBVAL);--PUTTING THE VALUE TO THE XML FILE 
    UTL_FILE.FCLOSE(FP);--CLOSING THE FILE
    DBMS_XMLGEN.CLOSECONTEXT(QWCTX);--CLOSING THE CONTEXT
    CLOSE MY_CUR;--CLOSING THR CURSOR 
END;

SELECT * FROM ALL_DIRECTORIES ;



/* FETCHING IT FROM THE FILE */

DECLARE 
    FP UTL_FILE.FILE_TYPE;--DEFINING THE FILE_POINTER VARIABLE
    BUFFER_VAR VARCHAR2(30000);
BEGIN
    FP:=UTL_FILE.FOPEN('EMP_DATA','EMP.XML','R');--OPENING THE FILE IN WRITE MODE
    LOOP
    UTL_FILE.GET_LINE(FP,BUFFER_VAR);--PUTTING THE VALUE TO THE XML FILE 
    DBMS_OUTPUT.PUT_LINE(BUFFER_VAR);
    END LOOP ;
    UTL_FILE.FCLOSE(FP);--CLOSING THE FILE
EXCEPTION
    WHEN NO_DATA_FOUND THEN 
        DBMS_OUTPUT.PUT_LINE('NO DATA FOUND ');
END;
    