CREATE OR REPLACE PROCEDURE INSERT_OLD_EMP_PROC
(
    P_TABLE IN VARCHAR2,
    P_COLUMN IN NUMBER
)
IS
    V_VAR VARCHAR2(50);
BEGIN
    -- V_VAR:='INSERT INTO ' || P_TABLE || ' VALUES' || '('|| P_COLUMN ||')';
    V_VAR:='INSERT INTO ' || P_TABLE || ' VALUES'(:X) USING(P_COLUMN) ;
    DBMS_OUTPUT.PUT_LINE(V_VAR);
    -- EXECUTE IMMEDIATE V_VAR;
END ;