
/* DROPPING THE EXISTING TABLE */
DROP TABLE TBL_XML

/*CREATING THE TABLE */
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE TBL_XML (DATA_VAL XMLTYPE)' ;
END;

/*CREATING AN ANONYMOUS BLOCK TO INSERT THE XML DATA  FROM THE DEPT TABLE TO TBL_XML TABLE */
DECLARE
    QWCTX DBMS_XMLGEN.CTXHANDLE ;
    MY_XML XMLTYPE ;
BEGIN
    QWCTX:=DBMS_XMLGEN.NEWCONTEXT('SELECT * FROM DEPT');--CREATING THE CONTEXT HANDLER
    MY_XML:=DBMS_XMLGEN.GETXMLTYPE(QWCTX);--FEEDING TO THE XMLTYPE VARIABLE 
    DBMS_XMLGEN.CLOSECONTEXT(QWCTX);--CLOSING THE CONTEXT
    INSERT INTO TBL_XML(DATA_VAL) VALUES (MY_XML);--INSERTING THE RESULT TO THE TABLE 
    DBMS_OUTPUT.PUT_LINE('iNSERTION SUCCESSFUL');
END ;

/* FETCHING THE DATA FROM THE CREATED TABLE */

SELECT * FROM DEPT

SELECT * FROM TBL_XML

SELECT 
    -- EXTRACT(VALUE(ROW_VAL) , 'ROW/DEPTNO'),
    -- EXTRACTVALUE(VALUE(ROW_VAL) , 'ROW/DEPTNO'),
    EXTRACTVALUE(VALUE(ROW_VAL) , 'ROW/DNAME')
FROM  TBL_XML , 
TABLE(XMLSEQUENCE(EXTRACT(DATA_VAL,'ROWSET/*'))) ROW_VAL;

/* SELECTING FROM THE VALUE */

SELECT 
    EXTRACTVALUE(VALUE(ROW_VAL) , 'ROW/LOC'),
    EXTRACTVALUE(VALUE(ROW_VAL) , 'ROW/DEPTNO'),
    EXTRACTVALUE(VALUE(ROW_VAL) , 'ROW/DNAME')
FROM  TBL_XML , 
TABLE(XMLSEQUENCE(EXTRACT(DATA_VAL,'ROWSET/ROW'))) ROW_VAL;

/*USING THE WHERE CLAUSE TO FETCH THE VALUE */

SELECT 
    EXTRACTVALUE(VALUE(ROW_VAL) , 'ROW/LOC') ,
    EXTRACTVALUE(VALUE(ROW_VAL) , 'ROW/DEPTNO'),
    EXTRACTVALUE(VALUE(ROW_VAL) , 'ROW/DNAME')
FROM  TBL_XML , 
TABLE(XMLSEQUENCE(EXTRACT(DATA_VAL,'ROWSET/ROW'))) ROW_VAL
WHERE EXTRACTVALUE(VALUE(ROW_VAL) , 'ROW/DEPTNO')=10;



