CREATE TABLE REBL_TBL(
    DATA NUMBER
)

DECLARE
    TYPE MY_NEST IS TABLE OF NUMBER ;
    V_VAR MY_NEST:=MY_NEST(2,4,6,8,10,12,14,16,18,20);
    TYPE MY_NEW_NEST IS TABLE  OF PLS_INTEGER;
    V_INDEX  MY_NEW_NEST := MY_NEW_NEST();
BEGIN
    V_INDEX.EXTEND;
    V_INDEX(1):=2;
    V_INDEX.EXTEND;
    V_INDEX(2):=5;
    V_INDEX.EXTEND;
    V_INDEX(3):=6;
    FORALL I IN VALUES OF V_INDEX
        INSERT INTO REBL_TBL(DATA) VALUES (V_VAR(I));
END;


DECLARE
    TYPE MY_NEST IS TABLE OF NUMBER ;
    V_VAR MY_NEST:=MY_NEST(2,4,6,8,10,12,14,16,18,20);
    TYPE MY_ARR IS TABLE  OF BINARY_INTEGER INDEX BY BINARY_INTEGER ;
    V_INDEX  MY_ARR ;
BEGIN
    V_INDEX(1):=2;
    V_INDEX(2):=5;
    V_INDEX(3):=6;
    V_INDEX(4):=7;
    FORALL I IN VALUES OF V_INDEX
        INSERT INTO REBL_TBL(DATA) VALUES (V_VAR(I));
END;

DROP TABLE REBL_TBL;

SELECT * FROM REBL_TBL;