BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE FUTR_TABL (DATA NUMBER )' ;
END ;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FUTR_TABL ' ;
END ;

DECLARE
    TYPE MY_NEST IS TABLE OF NUMBER ;
    V_VAR MY_NEST:=MY_NEST();
    TOTAL_VAL NUMBER;
BEGIN
    FOR I IN 1 .. 10
    LOOP
        V_VAR.EXTEND;
        V_VAR(V_VAR.LAST):=2*I;
    END LOOP;
    /*USING THE FORALL LOOP LOWER AND UPPER BOUND THEN */
    V_VAR.DELETE(4,7);--DELETING THE ELEMENT FROM THE COLLECTIOON TO MAKE FROM DENSE TO SPARSE COLLECTION
    FOR I IN 1..V_VAR.LAST--USING THE UPPER AND LOWER BOUND FOR THE SPARSE COLLECTION 
    LOOP
        IF V_VAR.EXISTS(I) THEN
            DBMS_OUTPUT.PUT_LINE('DATA EXIST');
        ELSE
            DBMS_OUTPUT.PUT_LINE('DATA DOESNOT EXIST');
        END IF ;
    END LOOP;
END ;


DECLARE
    TYPE MY_NEST IS TABLE OF NUMBER ;
    V_VAR MY_NEST:=MY_NEST();
    TOTAL_VAL NUMBER;
BEGIN
    FOR I IN 1 .. 10
    LOOP
        V_VAR.EXTEND;
        V_VAR(V_VAR.LAST):=2*I;
    END LOOP;
    /*USING THE FORALL LOOP LOWER AND UPPER BOUND THEN */
    V_VAR.DELETE(4,7);--DELETING THE ELEMENT FROM THE COLLECTIOON TO MAKE FROM DENSE TO SPARSE COLLECTION
    FORALL I IN INDICES OF V_VAR
        INSERT INTO FUTR_TABL(DATA) VALUES (V_VAR(I));
    
    SELECT COUNT(*) INTO TOTAL_VAL
    FROM  FUTR_TABL ;
    DBMS_OUTPUT.PUT_LINE('TOTAL_VALUE_INSERTED IS ' || TOTAL_VAL );
END ;