BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE FUTR_TABL (DATA NUMBER )' ;
END ;

DECLARE
    TYPE MY_NEST IS TABLE OF NUMBER ;
    V_VAR MY_NEST:=MY_NEST();
    TOTAL_VAL NUMBER;
BEGIN
    FOR I IN 1 .. 10
    LOOP
        V_VAR.EXTEND;
        V_VAR(V_VAR.LAST):=2*I;
    END LOOP;
    /*USING THE FORALL LOOP LOWER AND UPPER BOUND THEN */
    FORALL I IN 1..V_VAR.COUNT
        INSERT INTO FUTR_TABL(DATA) VALUES (V_VAR(I));
    
    SELECT COUNT(*) INTO TOTAL_VAL
    FROM FUTR_TABL;
    DBMS_OUTPUT.PUT_LINE('TOTAL_VALUE INSERTED IS ' || TOTAL_VAL );
END ;