CREATE OR REPLACE TYPE PERSON_OBJ_TY IS OBJECT(
    FNAME VARCHAR2(50),
    LNAME VARCHAR2(50),
    DOB DATE,
    CONSTRUCTOR FUNCTION PERSON_OBJ_TY
    (
        FIRST_NAME VARCHAR2,
        LAST_NAME VARCHAR2,
        DOB DATE
    )RETURN SELF AS RESULT ,
    MEMBER FUNCTION FULLNAME RETURN VARCHAR2,
    MEMBER FUNCTION ONDATE RETURN DATE
) NOT FINAL ;

/* CREATING THE TYPE BODY */

CREATE OR REPLACE TYPE BODY PERSON_OBJ_TY IS
CONSTRUCTOR FUNCTION PERSON_OBJ_TY
    (
        FIRST_NAME VARCHAR2,
        LAST_NAME VARCHAR2,
        DOB DATE
    )
RETURN SELF AS RESULT
IS 
BEGIN
    SELF.FNAME:=FIRST_NAME;
    SELF.LNAME:=LAST_NAME;
    SELF.DOB:=DOB;
    RETURN;
END PERSON_OBJ_TY ;
--CREATING THE FULLNAME FUNCTION 
MEMBER FUNCTION FULLNAME RETURN VARCHAR2
IS
    FULLNAME VARCHAR2(50);
BEGIN 
    FULLNAME:=SELF.FNAME || ' ' || SELF.LNAME ;
    RETURN FULLNAME ;
END FULLNAME ;
MEMBER FUNCTION ONDATE RETURN DATE
IS
BEGIN 
    RETURN SELF.DOB;
END ONDATE ;
END ;

/* DEROPPING THE OLD TABLE */
DROP TABLE PERSON_TBL;
/* CREATING THE COLUMN OBJECT OUT OF IT WITH OBJECT TABLE */
CREATE TABLE PERSON_TBL (
    ID NUMBER,
    DETAILS PERSON_OBJ
)

/* NOW INSERTING THE ELEMENTS INTO THE TABLE */
INSERT INTO PERSON_TBL(ID,DETAILS) VALUES (101,PERSON_OBJ(FIRST_NAME=>'RIKA',LAST_NAME=>'SARANGI',DOB=>TO_DATE('16-03-1997','DD-MM-YYYY')));
INSERT INTO PERSON_TBL(ID,DETAILS) VALUES (101,PERSON_OBJ(FIRST_NAME=>'ABISMRUTA',LAST_NAME=>'SARANGI',DOB=>TO_DATE('16-03-1997','DD-MM-YYYY')));
INSERT INTO PERSON_TBL(ID,DETAILS) VALUES (101,PERSON_OBJ(FIRST_NAME=>'ABI',LAST_NAME=>'SARANGI',DOB=>TO_DATE('16-03-1997','DD-MM-YYYY')));

/*SELECTING THE ELEMENTS*/
SELECT * FROM PERSON_TBL;

/*UPDATING THE ELEMNET VALUE */
UPDATE PERSON_TBL P SET ID=102 , P.DETAILS.LNAME='PRAYAG' WHERE P.DETAILS.FNAME='ABISMRUTA';
UPDATE PERSON_TBL P SET ID=103 , P.DETAILS.LNAME='PRAYAG' WHERE P.DETAILS.FNAME='ABI';

/*USING THE FUNCTION TO FETCH THE FUILL NAME AND DATE OF BIRTH */
SELECT P.DETAILS.FULLNAME() AS FULL_NAME, TO_CHAR(P.DETAILS.ONDATE(),'MM-DD-YYYY') AS DATE_OF_BIRTH FROM PERSON_TBL P;

DROP TYPE EMP_OBJ_TY;

/*NOW CREATING THE SUBTYPE OF PERSON WHICH IS OF EMP OBJECT TYPE BY INHERITING */

CREATE OR REPLACE TYPE EMP_OBJ_TY UNDER PERSON_OBJ_TY(
    JOB VARCHAR2(50),
    PSAL NUMBER,
    PALLOW NUMBER ,
    DOJ DATE ,
    MEMBER FUNCTION EARNING RETURN NUMBER,
    OVERRIDING MEMBER FUNCTION ONDATE RETURN DATE --OVERIDING THE ONDATE FUNCTION IN THE SUB CLASS
) FINAL ;
/*CREATING THE BODY FOR THE SUB TYPE */
CREATE OR REPLACE TYPE BODY EMP_OBJ_TY IS 
MEMBER FUNCTION EARNING RETURN NUMBER
IS
    SAL NUMBER;
BEGIN
    SAL:=SELF.PSAL+SELF.PALLOW ;
    SAL:=SAL*12;
    RETURN SAL;
END EARNING;
--WRITING THE FUNCTION FOR THE OVERIDING 
OVERRIDING MEMBER FUNCTION ONDATE RETURN DATE
IS 
BEGIN
    RETURN SELF.DOJ;
END ONDATE ;
END;

/*NOW CREATING THE TABLE USING THE SUB TYPE OBJECT */
CREATE TABLE EMP_DETAILS (
    ID NUMBER,
    DETAILS EMP_OBJ_TY
)

/* INSERTING THE DATE INTO THE VALUE OF THE EMPLOYEE */

INSERT INTO EMP_DETAILS(ID,DETAILS) VALUES (101,EMP_OBJ_TY(FNAME=>'RIKA',LNAME=>'SARANGI',DOB=>TO_DATE('16-03-1997','DD-MM-YYYY'),
JOB=>'INTERIOR DESIGNER', PSAL=>5000,PALLOW=>500,DOJ=>TO_DATE('10-02-2022','DD-MM-YYYY')));

INSERT INTO EMP_DETAILS(ID,DETAILS) VALUES (102,EMP_OBJ_TY(FNAME=>'ABI',LNAME=>'SARANGI',DOB=>TO_DATE('16-03-1997','DD-MM-YYYY'),
JOB=>'ARCHITECT ', PSAL=>5000,PALLOW=>500,DOJ=>TO_DATE('10-02-2022','DD-MM-YYYY')));

/*SELECTING THE  VALUE */

SELECT * FROM EMP_DETAILS ;

/*UPDATING THE VALUE */
UPDATE EMP_DETAILS E SET E.DETAILS.LNAME='PRAYAG' WHERE E.ID=102;

/*NOW FETCHING THE OVERIDEN METHOD AND OLD DOB AND EARNING FROM THE TABLE */
SELECT E.DETAILS.FULLNAME() AS FULL_NAME,E.DETAILS.ONDATE() DATE_OF_JOINING ,
E.DETAILS.DOB DATE_OF_BIRTH ,E.DETAILS.EARNING() AS ANNUAL_EARNING 
FROM EMP_DETAILS E;

COMMIT ;



