
/* CREATING THE OBJECT TYPE EMP_ITAX*/
CREATE OR REPLACE TYPE EMP_ITAX IS OBJECT(
    ID NUMBER,
    ENAME VARCHAR2(50),
    PSAL NUMBER,
    PALLOW NUMBER,
    PFUND NUMBER,
    PSAVE NUMBER,
    PTAX NUMBER,
    CONSTRUCTOR FUNCTION EMP_ITAX(
        VSAL NUMBER,
        VALLOW NUMBER,
        VFUND NUMBER,
        VSAVE NUMBER,
        VTAX NUMBER 
    ) RETURN  SELF AS RESULT,
    MEMBER FUNCTION GROSS_SAL RETURN NUMBER,
    MEMBER FUNCTION NET_INCOME RETURN NUMBER,
    MEMBER FUNCTION TAXABLE_AMT RETURN NUMBER,
    MEMBER FUNCTION INCM_TAX_AMT RETURN NUMBER
);

/* CREATING THE OBJECT-TYPE BODY AS */

CREATE OR REPLACE TYPE BODY EMP_ITAX IS
CONSTRUCTOR FUNCTION EMP_ITAX(
        VSAL NUMBER,
        VALLOW NUMBER,
        VFUND NUMBER,
        VSAVE NUMBER,
        VTAX NUMBER 
    ) 
RETURN SELF AS RESULT
IS
BEGIN
    SELF.PSAL:=VSAL;
    SELF.PALLOW:=VALLOW;
    SELF.PFUND:=VFUND;
    SELF.PSAVE:=VSAVE;
    SELF.PTAX:=VTAX;
    RETURN ;
END EMP_ITAX;
--DEFINING THE GROSS_SAL FUNCTION 
MEMBER FUNCTION GROSS_SAL RETURN NUMBER
IS
    SAL NUMBER;
BEGIN
    SAL:=SELF.PSAL+SELF.PALLOW ;
    SAL:=SAL*12;
    RETURN SAL ;
END GROSS_SAL ;
--DEFINING THE NET_INCOME FUNCTION 
MEMBER FUNCTION NET_INCOME RETURN NUMBER
IS
    SAL NUMBER;
BEGIN
    SAL:=SELF.GROSS_SAL() - ( SELF.GROSS_SAL() * (SELF.PFUND /100 )) ;
    RETURN SAL ;
END NET_INCOME ;
--DEFINING THE TAXABLE_AMT FUNCTION
MEMBER FUNCTION TAXABLE_AMT RETURN NUMBER
IS
    SAL NUMBER;
BEGIN
    SAL:=SELF.NET_INCOME() - ( SELF.PSAVE *12) ;
    RETURN SAL ;
END TAXABLE_AMT ;
--DEFINING THE INCOME_TAX AMOUNT 
MEMBER FUNCTION INCM_TAX_AMT RETURN NUMBER
IS
    SAL NUMBER;
BEGIN
    SAL:=SELF.TAXABLE_AMT() * ( SELF.PTAX/100) ;
    RETURN SAL ;
END INCM_TAX_AMT ;
END ;

/* NOW CREATING THE OBJECT TYPE TABLE OR OBJECT TABLE OUT OF IT */
CREATE TABLE EMP_TAX_TBL (
    ID NUMBER,
    EMO_NAME VARCHAR2(50),
    OBJ_COL_TAX EMP_ITAX
)

/* NOW IF WE WANT TO INSERT THE VALUES INTO THIS WE CAN USE IT AS */

INSERT INTO EMP_TAX_TBL (ID,EMO_NAME,OBJ_COL_TAX) VALUES('101','RIKA',EMP_ITAX(3000,500,13,500,10));
INSERT INTO EMP_TAX_TBL (ID,EMO_NAME,OBJ_COL_TAX) VALUES('102','ABI',EMP_ITAX(3000,700,12,600,10));
INSERT INTO EMP_TAX_TBL (ID,EMO_NAME,OBJ_COL_TAX) VALUES('103','GUNDU',EMP_ITAX(3000,800,11,700,10));
INSERT INTO EMP_TAX_TBL (ID,EMO_NAME,OBJ_COL_TAX) VALUES('104','ABISMRUTA',EMP_ITAX(3000,900,14,900,10));

/* NOW SELECTING THE VALUE INTO IT */

COLUMN OBJ_COL_TAX FORMAT A50

SELECT E.ID,E.EMO_NAME,E.OBJ_COL_TAX
FROM EMP_TAX_TBL E;

/*UPDATING THE VALUE AS */

UPDATE EMP_TAX_TBL E SET E.OBJ_COL_TAX.PSAL=5000 WHERE ID=101

/*SELECTING THE FUNCTIONS WITH CORRESPONDING VALUE FROM THE COLUMN OBJECT OBJECT TRYPE FUNCTIONS  */

SELECT E.EMO_NAME,E.OBJ_COL_TAX.GROSS_SAL(),E.OBJ_COL_TAX.NET_INCOME(),E.OBJ_COL_TAX.TAXABLE_AMT(),E.OBJ_COL_TAX.INCM_TAX_AMT()
FROM EMP_TAX_TBL E










