CREATE OR REPLACE DIRECTORY EMP_DATA AS 'SALES';

DROP DIRECTORY EMP_DATA ;


GRANT EXECUTE ON UTL_FILE TO PRAT;

GRANT EXECUTE ON SYS.utl_file TO PRAT ;

GRANT CREATE ANY DIRECTORY TO PRAT ;

GRANT READ , WRITE ON DIRECTORY EMP_DATA TO PRAT ;

grant execute on utl_file to system;

GRANT EXECUTE on UTL_FILE to PRAT ;

grant execute on utl_file to PRAT

SELECT value FROM v$parameter WHERE name = 'utl_file_dir';

SHOW USER ;

SELECT ENAME FROM EMP;


SET SERVEROUTPUT ON 
SET LINE 100
SET PAGESIZE 50
DECLARE
    FP  UTF_FILE.FILE_TYPE ;
    CURSOR MY_CUR IS SELECT ENAME FROM EMP ;
    TYPE MY_NEST IS TABLE OF EMP.ENAME%TYPE;
    V_ENAME  EMP.ENAME%TYPE;
BEGIN
    FP:=UTF_FILE.FOPEN('EMO_DB','EMP_DATA.TXT','A');
    UTF.PUTF(FP,'ABCDEF');
    UTF_FILE.FCLOSE(FP);
END;
/
    
DECLARE
    FP  UTL_FILE.FILE_TYPE ;
BEGIN
    FP:=UTL_FILE.FOPEN('EMP_DATA','EMP_DATA.txt','W');
    UTL_FILE.PUTF(FP,'ABCDEF');
    UTL_FILE.FCLOSE(FP);
END;
/

DECLARE
    FP  UTL_FILE.FILE_TYPE ;
    BUFFER_VAR VARCHAR2(50);
BEGIN
    FP:=UTL_FILE.FOPEN('EMP_DATA','EMP_DATA.txt','R');
--    UTL_FILE.PUTF(FP,'ABCDEF');
    UTL_FILE.GET_LINE(FP,BUFFER_VAR);
    DBMS_OUTPUT.PUT_LINE(BUFFER_VAR);
    UTL_FILE.FCLOSE(FP);
END;
/


SELECT DISTINCT SUBSTR (file_name,
                        1,
                        INSTR (file_name,
                               '/',
                               -1,
                               1))
  FROM DBA_DATA_FILES
 WHERE tablespace_name = 'SYSTEM';
 
 
 
 SELECT * FROM ALL_DIRECTORIES ;
 
 SELECT * FROM DBMS_CLOUD.LIST_FILES('STAGING');
 
 
 SELECT * FROM EMP;
 
 SET SERVEROUTPUT ON
 SET LINE 100
 SET PAGE 50
 DESCRIBE UTL_FILE ;
 
 
 REM INSERTING into EXPORT_TABLE
SET DEFINE OFF;
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7200,'PRATIK',null,null,null,2500,null,20);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7300,'RIKA',null,null,null,2500,null,50);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7369,'SMITH','CLERK',7902,to_date('17-DEC-80','DD-MON-RR'),800,null,20);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7499,'ALLEN','SALESMAN',7698,to_date('20-FEB-81','DD-MON-RR'),1600,300,30);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7521,'WARD','SALESMAN',7698,to_date('22-FEB-81','DD-MON-RR'),1250,500,30);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7566,'JONES','MANAGER',7839,to_date('02-APR-81','DD-MON-RR'),2975,null,20);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7654,'MARTIN','SALESMAN',7698,to_date('28-SEP-81','DD-MON-RR'),1250,1400,30);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7698,'BLAKE','MANAGER',7839,to_date('01-MAY-81','DD-MON-RR'),2850,null,30);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7782,'CLARK','MANAGER',7839,to_date('09-JUN-81','DD-MON-RR'),2450,null,10);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7788,'SCOTT','ANALYST',7566,to_date('09-DEC-82','DD-MON-RR'),3000,null,20);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7839,'KING','PRESIDENT',null,to_date('17-NOV-81','DD-MON-RR'),5000,null,10);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7844,'TURNER','SALESMAN',7698,to_date('08-SEP-81','DD-MON-RR'),1500,0,30);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7876,'ADAMS','CLERK',7788,to_date('12-JAN-83','DD-MON-RR'),1100,null,20);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7900,'JAMES','CLERK',7698,to_date('03-DEC-81','DD-MON-RR'),950,null,30);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7902,'FORD','ANALYST',7566,to_date('03-DEC-81','DD-MON-RR'),3000,null,20);
Insert into EXPORT_TABLE (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO) values (7934,'MILLER','CLERK',7782,to_date('23-JAN-82','DD-MON-RR'),1300,null,10);

 GRANT EXECUTE ON UTL_MAIL TO PRAT ;
 
 SELECT ECHO $ORACLE_HOME FROM DUAL;
 
 DESCRIBE  UTL_MAIL
 
 
 
 
    
    