CREATE OR REPLACE TYPE ITAX IS OBJECT(
    ID NUMBER,
    ENAME VARCHAR2(50),
    PSAL NUMBER ,
    PALLOW NUMBER,
    PFUND NUMBER ,
    PSAVE NUMBER ,
    PTAX NUMBER,
    MEMBER FUNCTION GROSS_SAL RETURN NUMBER,
    MEMBER FUNCTION NET_INCOME RETURN NUMBER ,
    MEMBER FUNCTION TAXABLE_AMOUNT RETURN NUMBER,
    MEMBER FUNCTION INCOMETAX_AMT RETURN NUMBER
    
);--CREATING THE TYPE HEADER FOR THE OBJECT TYPE I.E THE CLASS  


CREATE OR REPLACE TYPE BODY ITAX IS --CREATING THE THYPE BODY 
MEMBER FUNCTION GROSS_SAL RETURN NUMBER
IS 
    SAL NUMBER ;
BEGIN 
    SAL:=SELF.PSAL+SELF.PALLOW;--CALCULATING ON MONTHLY INCOME WITH ALLOWANCES
    SAL:=SAL*12;--CALCULATING FOR ANNUAL BASIS
    RETURN SAL;
END GROSS_SAL ;--CLOSING THE MEMBER FUNCTION 
--NOW CREATING THE FUNCTION FOR THE NET_INCOME IS 
MEMBER FUNCTION NET_INCOME RETURN NUMBER
IS 
    NET NUMBER ;
BEGIN 
    NET:=SELF.GROSS_SAL()-(SELF.GROSS_SAL() * (SELF.PFUND/100));--CALCULATING THE ANNUAL NET INCOME 
    RETURN NET;
END NET_INCOME ;--CLOSING THE MEMBER FUNCTION 
--CALCULATING FOR THE TAXABLE AMOUNT AS NET_INCOME-SAVING 
MEMBER FUNCTION TAXABLE_AMOUNT RETURN NUMBER
IS 
    AMOUNT NUMBER ;
BEGIN 
    AMOUNT:=(SELF.NET_INCOME()-(SELF.PSAVE * 12 ));--CALCULATING THE ANNUAL SAVINGS 
    RETURN AMOUNT;
END TAXABLE_AMOUNT ;--CLOSING THE MEMBER FUNCTION 
--NOW CALCULATING FOR THE INCOMETAX_AMOUNT AS 
MEMBER FUNCTION INCOMETAX_AMT RETURN NUMBER
IS 
    AMT NUMBER ;
BEGIN 
    AMT:=(SELF.TAXABLE_AMOUNT() * (SELF.PTAX/100) );--CALCULATING THE ANNUAL SAVINGS 
    RETURN AMT;
END INCOMETAX_AMT ;--CLOSING THE MEMBER FUNCTION 
END; --CLOSING THE INCOMETAX AMOUNT 

/* EXECUTING THE PROCEDURE THAT WE CREATED */

SET DEFINE ON 
DECLARE
    V_ID NUMBER;
    V_ENAME VARCHAR2(50);
    V_PSAL NUMBER;
    V_PALLOW NUMBER;
    V_PFUND NUMBER ;
    V_PSAVE NUMBER ;
    V_PTAX NUMBER;
    OBJ_ITAX  ITAX;
BEGIN 
    V_ID:=&V_ID;
    V_ENAME:='&V_ENAME';
    V_PSAL:=&V_PSAL;
    V_PALLOW:=&V_PALLOW;
    V_PFUND:=&V_PFUND;
    V_PSAVE:=&V_PSAVE;
    V_PTAX:=&V_PTAX;
    OBJ_ITAX:=ITAX(ID=>V_ID,ENAME=>V_ENAME,PSAL=>V_PSAL,PALLOW=>V_PALLOW,PFUND=>V_PFUND,PSAVE=>V_PSAVE,PTAX=>V_PTAX);
    DBMS_OUTPUT.PUT_LINE('ALL ITAX OBJECT RELATED DETAILS ');
    DBMS_OUTPUT.PUT_LINE('ID OF THE PERSON IS ' || V_ID);
    DBMS_SESSION.SLEEP(1);
    DBMS_OUTPUT.PUT_LINE('NAME OF THE PERSON IS ' || V_ENAME);
    DBMS_LOCK.SLEEP(1);
    DBMS_OUTPUT.PUT_LINE(' GROSS SALARY OF THE PERSON IS ' ||  OBJ_ITAX.GROSS_SAL());
    DBMS_SESSION.SLEEP(1);
    DBMS_OUTPUT.PUT_LINE('NET INCOME OF THE PERSON IS ' || OBJ_ITAX.NET_INCOME());
    DBMS_LOCK.SLEEP(1);
    DBMS_OUTPUT.PUT_LINE('TAXABLE_AMOUNT OF THE PERSON IS ' || OBJ_ITAX.TAXABLE_AMOUNT());
    DBMS_LOCK.SLEEP(1);
    DBMS_OUTPUT.PUT_LINE('INCOME TAX OF THE PERSON IS ' || OBJ_ITAX.INCOMETAX_AMT());
END;




