

SELECT ENAME,SAL,
SUM(SAL) OVER (ORDER BY SAL ROWS BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING ) AS SUM_SAL
FROM EMP;


SELECT ENAME,SAL,HIREDATE,
RANK() OVER(ORDER BY HIREDATE ) AS RANK_HIRE
FROM EMP ;

SELECT ENAME,SAL,HIREDATE,
RANK() OVER(ORDER BY HIREDATE DESC ) AS RANK_HIRE
FROM EMP ;

SELECT ENAME,SAL,HIREDATE,
RANK() OVER(ORDER BY SAL DESC ) AS RANK_HIRE
FROM EMP ;

SELECT ENAME,SAL,HIREDATE,
ROW_NUMBER () OVER(ORDER BY SAL DESC ) AS RANK_HIRE
FROM EMP ;

SELECT ENAME,SAL,HIREDATE,
DENSE_RANK() OVER(ORDER BY SAL DESC ) AS RANK_HIRE
FROM EMP ;

SELECT ENAME,SAL,HIREDATE,
DENSE_RANK() OVER(ORDER BY HIREDATE ) AS RANK_HIRE
FROM EMP ;

SELECT ENAME,SAL,HIREDATE,
RANK() OVER(ORDER BY HIREDATE DESC ) AS RANK_HIRE
FROM EMP ;


SELECT ENAME,SAL,DEPTNO,
SUM(SAL) OVER(PARTITION BY DEPTNO ORDER BY SAL RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW ) AS AVG_SAL
FROM EMP ;