DECLARE
    QWCTX DBMS_XMLGEN.CTXHANDLE ;
    RESULT_VAR CLOB ;
BEGIN
    QWCTX:=DBMS_XMLGEN.NEWCONTEXT('SELECT * FROM DEPT');
    DBMS_XMLGEN.SETROWSETTAG(QWCTX,'DEPT_DETAILS');
    DBMS_XMLGEN.SETROWTAG(QWCTX,'DEPT');
    RESULT_VAR:=DBMS_XMLGEN.GETXML(QWCTX);
    DBMS_OUTPUT.PUT_LINE(RESULT_VAR);
END;



DECLARE
    QWCTX DBMS_XMLGEN.CTXHANDLE ;
    RESULT_VAR XMLTYPE ;
BEGIN
    QWCTX:=DBMS_XMLGEN.NEWCONTEXT('SELECT * FROM DEPT');
    DBMS_XMLGEN.SETROWSETTAG(QWCTX,'DEPT_DETAILS');
    DBMS_XMLGEN.SETROWTAG(QWCTX,'DEPT');
    RESULT_VAR:=DBMS_XMLGEN.GETXMLTYPE(QWCTX);
    DBMS_OUTPUT.PUT_LINE(RESULT_VAR.GETCLOBVAL);
END;


