

/* OVER RIDING THE STANDARD TO_CHAR FUNCTION */

CREATE OR REPLACE PACKAGE CHAR_PKG IS
PROCEDURE TO_CHAR (
    P_INT_1 IN NUMBER,
    P_INT_2 IN NUMBER
);
END CHAR_PKG ;

CREATE OR REPLACE PACKAGE BODY CHAR_PKG IS
PROCEDURE TO_CHAR
(
    P_INT_1 IN NUMBER,
    P_INT_2 IN NUMBER
)
IS
    V_CHAR_1 VARCHAR2(50);
    V_CHAR_2 VARCHAR2(50);
    V_RESULT VARCHAR2(50);
BEGIN
    V_CHAR_1:=STANDARD.TO_CHAR(P_INT_1);
    V_CHAR_2:=STANDARD.TO_CHAR(P_INT_2);
    V_RESULT:=V_CHAR_1 || V_CHAR_2;
    DBMS_OUTPUT.PUT_LINE('RESULT IS ' || V_RESULT);
END TO_CHAR ;
END CHAR_PKG;


/*CALLING THE PACKAGE */
BEGIN
CHAR_PKG.TO_CHAR(P_INT_1=>10,P_INT_2=>20);
END;





