DECLARE
    TYPE MY_CUR IS REF CURSOR;
    V_CUR MY_CUR;
    V_VAR EMP.ENAME%TYPE;
BEGIN
    OPEN V_CUR FOR SELECT ENAME FROM EMP;
    LOOP
        FETCH V_CUR INTO V_VAR ;
        EXIT WHEN V_CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_VAR); 
    END LOOP;
    CLOSE V_CUR;
END;


/*USING THE STRONG REF CURSOR FORT THE SAME */
/*REMEMBER THAT STRONG REF CURSOR WILL RETURN THE ROWTYPE NOT THE ANCHOR TYPE */
DECLARE
    TYPE MY_CUR IS REF CURSOR RETURN EMP%ROWTYPE;
    V_CUR MY_CUR;
    V_VAR EMP%ROWTYPE ;
BEGIN
    OPEN V_CUR FOR SELECT * FROM EMP;
    LOOP
        FETCH V_CUR INTO V_VAR ;
        EXIT WHEN V_CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_VAR.ENAME); 
    END LOOP;
    CLOSE V_CUR;
END;