/* UNDERSTANDING THE TABLE FUNCTION */
SELECT * FROM 
(SELECT MAX(DEPTNO) FROM DEPT );

/*CREATING THE NESTED TYPE */
CREATE OR REPLACE TYPE MY_NEST IS TABLE OF VARCHAR2(255);

/* CREATING THE VARRAY TYPE */
CREATE OR REPLACE TYPE MY_VARR IS VARRAY (10) OF VARCHAR2(255);

/*CREATING THE TABLE OF NESTED TABLE COLUMN */

CREATE TABLE TBL_COL (
    ID NUMBER,
    NAME VARCHAR2(255),
    MY_COL  MY_NEST 
) 
NESTED TABLE MY_COL STORE AS MY_COL_DETAILS

DESCRIBE TBL_COL

/*INSERTING THE  VALUES */

INSERT INTO TBL_COL(ID,NAME,MY_COL) VALUES (1001,'RIKA',MY_NEST('PRATIK','RIKA'))

/* RETRIEVING THE VALUE */

SELECT ID,NAME,MY_COL_DETAILS.*
FROM TBL_COL ,
TABLE(TBL_COL.MY_COL);

SELECT T.ID,T.NAME,M.*
FROM TBL_COL T,
TABLE(T.MY_COL) M;

/*CREATING THE TABLE OF VARRAY TABLE COLUMN */

CREATE TABLE TBL_COL_VARR (
    ID NUMBER,
    NAME VARCHAR2(255),
    MY_COL  MY_VARR
) 

/* INSERTING THE VALUE */

INSERT INTO TBL_COL_VARR (ID,NAME,MY_COL) VALUES (1001,'RIKA',MY_VARR('PRATIK','RIKA'))

/* RETRIEVING THE VALUE */

SELECT T.ID,T.NAME,M.*
FROM TBL_COL_VARR T,
TABLE(T.MY_COL) M;


/* USING THE TABLE FUNCTION ON THEM */--FROM ORACLE 11G AND LESS

SELECT * FROM 
TABLE(MY_VARR('RIKA','GUNDU','ABI'));

/* USING THE TABLE FUNCTION IMPLICITLY */--FROM ORACLE 12G ONWARDS

SELECT * FROM 
(MY_VARR('RIKA','GUNDU','ABI'));


/* CREATING A FUNCTION WHICH WILL RETURN THE COLLECTION WHICH CAN ACT AS TABLE INSIDE THE SELECT QUERY */

CREATE OR REPLACE TYPE MYTYPE IS TABLE OF VARCHAR2(255); 

CREATE OR REPLACE FUNCTION FUNC_COLL 
RETURN MYTYPE
IS
    V_VAR MYTYPE:=MYTYPE() ;--DECLARING AND INITIALIZING THE VALUE
BEGIN 
    FOR I IN (SELECT ENAME FROM EMP)
    LOOP
        V_VAR.EXTEND ;
        V_VAR(V_VAR.LAST):=i.ENAME;
    END LOOP ;
    RETURN V_VAR ;
END;


/*CALLING IT DIRECTLY*/

SELECT * FROM 
FUNC_COLL();

/*CALLING IT WITH TABLE FUNCTION  DIRECTLY*/

SELECT * FROM 
TABLE(FUNC_COLL());















