DECLARE
    FP  UTL_FILE.FILE_TYPE ;
BEGIN
    FP:=UTL_FILE.FOPEN('EMP_DATA','EMP_DATA.txt','W');
    UTL_FILE.PUTF(FP,'ABCDEF');
    UTL_FILE.FCLOSE(FP);
END;
/

DECLARE
    FP  UTL_FILE.FILE_TYPE ;
    BUFFER_VAR VARCHAR2(50);
BEGIN
    FP:=UTL_FILE.FOPEN('EMP_DATA','EMP_DATA.txt','R');
--    UTL_FILE.PUTF(FP,'ABCDEF');
    UTL_FILE.GET_LINE(FP,BUFFER_VAR);
    DBMS_OUTPUT.PUT_LINE(BUFFER_VAR);
    UTL_FILE.FCLOSE(FP);
END;
/


DECLARE
    FP UTL_FILE.FILE_TYPE ;
    CURSOR MY_CUR IS SELECT ENAME FROM ADMIN.EMP ;
    V_ENAME ADMIN.EMP.ENAME%TYPE;
BEGIN
    FP:=UTL_FILE.FOPEN('EMP_DATA','EMP2.TXT','W');
    OPEN MY_CUR;
    LOOP
        FETCH MY_CUR INTO V_ENAME ;
        EXIT WHEN MY_CUR%NOTFOUND ;
        UTL_FILE.PUT_LINE(FP,V_ENAME);
    END LOOP ;
    DBMS_OUTPUT.PUT_LINE('FILE_CREATED SUCCESSFULLY');
    UTL_FILE.FCLOSE(FP);
    CLOSE MY_CUR;
END;

/* READING FROM THE FILE */

DECLARE
    FP UTL_FILE.FILE_TYPE ;
--    CURSOR MY_CUR IS SELECT ENAME FROM ADMIN.EMP ;
    V_ENAME VARCHAR2(50);
        BUFFER_VAR VARCHAR2(50);
        STATUS_VAR PLS_INTEGER ;
BEGIN
    FP:=UTL_FILE.FOPEN('EMP_DATA','EMP2.TXT','R');
    FOR I IN 1 ..14
    LOOP
        UTL_FILE.GET_LINE(FP,BUFFER_VAR);
        DBMS_OUTPUT.PUT_LINE(BUFFER_VAR);
    END LOOP;
END;
    
    