CREATE TABLE TBL_XML (DATA XMLTYPE);

/* FETCHING THE LIMITED DATA IN THE ROWS BY USING THE SETMAXROWS AND GETNUMROWSPROGRESSED FUNCTION */

DECLARE
    QWCTX DBMS_XMLGEN.CTXHANDLE;
    RESULT_VAR XMLTYPE ;
BEGIN
    QWCTX:=DBMS_XMLGEN.NEWCONTEXT('SELECT * FROM DEPT');
    DBMS_XMLGEN.SETMAXROWS(QWCTX,1);
    LOOP
        RESULT_VAR:=DBMS_XMLGEN.GETXMLTYPE(QWCTX);
        EXIT WHEN DBMS_XMLGEN.GETNUMROWSPROCESSED(QWCTX) =0 ; 
        INSERT INTO TBL_XML(DATA) VALUES (RESULT_VAR);
    END LOOP;
END ;

SELECT * FROM TBL_XML;

/* FORMATING THE XML INTO SPACE AND UNSPACE VALUE AS &LT; &GT;*/

DECLARE
    V_XML XMLTYPE;
    V_CLOB CLOB;
    V_STR VARCHAR2(3000);
    RESULT_VAR VARCHAR2(3000);
BEGIN
    SELECT DBMS_XMLGEN.GETXMLTYPE('SELECT * FROM DEPT')
    INTO V_XML
    FROM DUAL ;
    V_CLOB:=V_XML.GETCLOBVAL;
    V_STR:=STANDARD.TO_CHAR(V_CLOB);
    RESULT_VAR:=DBMS_XMLGEN.CONVERT(V_STR,0);
    DBMS_OUTPUT.PUT_LINE(RESULT_VAR);
END ;


SELECT * FROM V$VERSION;
